import Cloning.TensorCartanInclusion
import Cloning.TensorHighestGramIntertwiner

/-! Exact Lie intertwining and range of the literal physical Cartan inclusion. -/
noncomputable section
open scoped BigOperators InnerProductSpace
namespace Cloning.TensorLie
set_option maxHeartbeats 1000000
set_option backward.isDefEq.respectTransparency false
variable {d : ℕ}

def partitionGenerator (mu : Fin d → ℕ) (hmu : Antitone mu) (a b : Fin d) :
    cyclicSector (partitionHighestTensor mu hmu) →L[ℂ] cyclicSector (partitionHighestTensor mu hmu) :=
  cyclicGenerator _ (fun i => (mu i : ℂ))
    (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) a b

def productPartitionGenerator
    (mu nu : Fin d → ℕ) (hmu : Antitone mu) (hnu : Antitone nu) (a b : Fin d) :
    tensorProductSector (cyclicSector (partitionHighestTensor mu hmu))
        (cyclicSector (partitionHighestTensor nu hnu)) →L[ℂ]
      tensorProductSector (cyclicSector (partitionHighestTensor mu hmu))
        (cyclicSector (partitionHighestTensor nu hnu)) :=
  ((collectiveGenerator ((∑ i, mu i) + ∑ i, nu i) a b).comp
    (tensorProductSector (cyclicSector (partitionHighestTensor mu hmu))
      (cyclicSector (partitionHighestTensor nu hnu))).subtypeL).codRestrict _
    (fun x => tensorProductSector_generator_invariant _ _
      (fun a b y hy => cyclicSector_generator_invariant _ (fun i => (mu i : ℂ))
        (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) a b hy)
      (fun a b y hy => cyclicSector_generator_invariant _ (fun i => (nu i : ℂ))
        (partitionHighestTensor_cartan nu hnu) (partitionHighestTensor_raising_zero nu hnu) a b hy)
      a b x.property)

/-- The constructed Cartan inclusion intertwines every actual restricted
matrix-unit generator on the full sum-weight sector. -/
theorem cartanInclusion_intertwines
    (mu nu : Fin d → ℕ) (hmu : Antitone mu) (hnu : Antitone nu) (a b : Fin d)
    (x : cyclicSector (partitionHighestTensor (fun i => mu i + nu i)
      (sumPartition_antitone mu nu hmu hnu))) :
    cartanInclusion mu nu hmu hnu
        (partitionGenerator (fun i => mu i + nu i) (sumPartition_antitone mu nu hmu hnu) a b x) =
      productPartitionGenerator mu nu hmu hnu a b (cartanInclusion mu nu hmu hnu x) := by
  apply Subtype.ext
  exact congrArg (fun z : cyclicSector (cartanHighest mu nu hmu hnu) =>
    (z : TensorRegister ((∑ i, mu i) + ∑ i, nu i) (Fin d)))
    (highestCyclicIsometry_intertwines _ _ (fun i => ((mu i + nu i : ℕ) : ℂ))
      (partitionHighestTensor_cartan _ _) (cartanHighest_cartan mu nu hmu hnu)
      (partitionHighestTensor_raising_zero _ _) (cartanHighest_raising_zero mu nu hmu hnu)
      (partitionHighestTensor_norm _ _) (cartanHighest_norm mu nu hmu hnu) a b x)

/-- The same inclusion viewed as an actual isometry into the full physical
concatenated tensor register. Its range is identified exactly below. -/
def cartanAmbientInclusion
    (mu nu : Fin d → ℕ) (hmu : Antitone mu) (hnu : Antitone nu) :
    cyclicSector (partitionHighestTensor (fun i => mu i + nu i) (sumPartition_antitone mu nu hmu hnu))
      →ₗᵢ[ℂ] TensorRegister ((∑ i, mu i) + ∑ i, nu i) (Fin d) :=
  (tensorProductSector (cyclicSector (partitionHighestTensor mu hmu))
    (cyclicSector (partitionHighestTensor nu hnu))).subtypeₗᵢ.comp
    (cartanInclusion mu nu hmu hnu)

theorem cartanAmbientInclusion_intertwines
    (mu nu : Fin d → ℕ) (hmu : Antitone mu) (hnu : Antitone nu) (a b : Fin d)
    (x : cyclicSector (partitionHighestTensor (fun i => mu i + nu i)
      (sumPartition_antitone mu nu hmu hnu))) :
    cartanAmbientInclusion mu nu hmu hnu
        (partitionGenerator (fun i => mu i + nu i) (sumPartition_antitone mu nu hmu hnu) a b x) =
      collectiveGenerator ((∑ i, mu i) + ∑ i, nu i) a b (cartanAmbientInclusion mu nu hmu hnu x) :=
  congrArg Subtype.val (cartanInclusion_intertwines mu nu hmu hnu a b x)

/-- The image is exactly the cyclic subspace generated by the product highest
tensor, rather than merely an unspecified invariant subspace. -/
theorem cartanAmbientInclusion_range
    (mu nu : Fin d → ℕ) (hmu : Antitone mu) (hnu : Antitone nu) :
    LinearMap.range (cartanAmbientInclusion mu nu hmu hnu).toLinearMap =
      cyclicSector (cartanHighest mu nu hmu hnu) := by
  ext z
  constructor
  · rintro ⟨x, rfl⟩
    exact (cartanCyclicIsometry mu nu hmu hnu x).property
  · intro hz
    refine ⟨(cartanCyclicIsometry mu nu hmu hnu).symm ⟨z, hz⟩, ?_⟩
    exact congrArg Subtype.val ((cartanCyclicIsometry mu nu hmu hnu).apply_symm_apply ⟨z, hz⟩)

end Cloning.TensorLie
