import Cloning.TensorFlatProjectorGibbs

/-! Exact rank compression of arbitrary diagonal sector Gibbs states. The
operator identity is valid for every real spectrum; nonnegativity enters only
the equality of the trace-normalization constants. -/
noncomputable section
open scoped BigOperators InnerProductSpace ComplexOrder Matrix
namespace Cloning.TensorLie
open Cloning.PCT Cloning.InfiniteTraceClass Cloning.Hybrid
set_option maxHeartbeats 1600000
set_option synthInstance.maxHeartbeats 200000
set_option backward.isDefEq.respectTransparency false
variable {n r k : ℕ}
local instance (n d : ℕ) : FiniteDimensional ℂ (TensorRegister n (Fin d)) :=
  (registerBasis (Fin n → Fin d)).toOrthonormalBasis.toBasis.finiteDimensional_of_finite

/-- Extend an arbitrary supported spectrum by zero coordinates. -/
def padSpectrum (p : Fin r → ℝ) (k : ℕ) : Fin (r+k) → ℝ :=
  Fin.addCases p (fun _ => 0)

@[simp] theorem padSpectrum_left (p : Fin r → ℝ) (k : ℕ) (a : Fin r) :
    padSpectrum p k (Fin.castAdd k a)=p a := by simp [padSpectrum]

@[simp] theorem padSpectrum_right (p : Fin r → ℝ) (k : ℕ) (a : Fin k) :
    padSpectrum p k (Fin.natAdd r a)=0 := by simp [padSpectrum]

theorem padSpectrum_nonneg (p : Fin r → ℝ) (hp : ∀a,0≤p a) (k : ℕ) :
    ∀a,0≤padSpectrum p k a := by
  intro a
  induction a using Fin.addCases <;> simp [hp]

/-- Literal zero extension of the diagonal tensor power along the coordinate
isometry. This establishes the rank identity before taking Schur blocks. -/
theorem tensorOperator_padSpectrum (p : Fin r → ℝ) :
    tensorOperator n (Matrix.diagonal (fun a => (padSpectrum p k a : ℂ))) =
      (coordinateTensorEmbedding n r k).toContinuousLinearMap.comp
        ((tensorOperator n (Matrix.diagonal (fun a => (p a : ℂ)))).comp
          (coordinateTensorEmbedding n r k).toContinuousLinearMap.adjoint) := by
  ext y w
  rw [tensorOperator_diagonal_apply]
  by_cases hw : ∀t,(w t).val<r
  · obtain ⟨v,rfl⟩ := (coordinateWordEmbedding_range w).mpr hw
    change _ = coordinateTensorEmbedding n r k
      (tensorOperator n (Matrix.diagonal (fun a => (p a : ℂ)))
        ((coordinateTensorEmbedding n r k).toContinuousLinearMap.adjoint y))
          (coordinateWordEmbedding n r k v)
    rw [coordinateTensorEmbedding,registerEmbedding_apply_image,
      tensorOperator_diagonal_apply,registerEmbedding_adjoint_apply]
    simp only [coordinateWordEmbedding,Function.Embedding.coeFn_mk,padSpectrum_left]
  · have hz : (∏t : Fin n,(padSpectrum p k (w t) : ℂ))=0 := by
      push_neg at hw
      obtain ⟨t,ht⟩ := hw
      apply Finset.prod_eq_zero (Finset.mem_univ t)
      have hright : ∃a : Fin k, Fin.natAdd r a=w t := by
        exact ⟨⟨(w t).val-r,by have := (w t).isLt; omega⟩,Fin.ext (by dsimp; omega)⟩
      obtain ⟨a,ha⟩ := hright
      rw [← ha,padSpectrum_right,Complex.ofReal_zero]
    rw [hz,zero_mul]
    exact (registerEmbedding_apply_not_mem _ _ w
      (fun he => hw ((coordinateWordEmbedding_range w).mp he))).symm

/-- The literal rank identity restricted to the cyclic sector generated by an
embedded highest tensor. -/
theorem coordinateSectorEmbedding_gibbs
    (Ω : TensorRegister n (Fin r)) (mu : Fin r → ℕ)
    (hweight : ∀a,collectiveGenerator n a a Ω=(mu a : ℂ) • Ω)
    (hraise : ∀a b,a<b → collectiveGenerator n a b Ω=0) (p : Fin r → ℝ) :
    sectorGibbsOperator (coordinateTensorEmbedding n r k Ω) (padPartition mu k)
      (coordinateTensorEmbedding_highest Ω mu hweight hraise).1
      (coordinateTensorEmbedding_highest Ω mu hweight hraise).2 (padSpectrum p k) =
    (coordinateSectorEmbedding (k := k) Ω).toContinuousLinearMap.comp
      ((sectorGibbsOperator Ω mu hweight hraise p).comp
        (coordinateSectorEmbedding (k := k) Ω).toContinuousLinearMap.adjoint) := by
  apply ContinuousLinearMap.ext
  intro x
  apply Subtype.ext
  change tensorOperator n (Matrix.diagonal (fun a => (padSpectrum p k a : ℂ)))
      (x : TensorRegister n (Fin (r+k))) =
    coordinateTensorEmbedding n r k
      (tensorOperator n (Matrix.diagonal (fun a => (p a : ℂ)))
        (((coordinateSectorEmbedding (k := k) Ω).toContinuousLinearMap.adjoint x : cyclicSector Ω) :
          TensorRegister n (Fin r)))
  rw [coordinateSectorEmbedding_adjoint_coe,tensorOperator_padSpectrum]
  rfl

/-- Exact unnormalized Gibbs compression in the canonical physical sectors. -/
theorem sectorGibbsOperator_padSpectrum (mu : Fin r → ℕ) (hmu : Antitone mu)
    (k : ℕ) (p : Fin r → ℝ) :
    sectorGibbsOperator
      (partitionHighestTensor (padPartition mu k) (padPartition_antitone mu hmu k))
      (padPartition mu k) (partitionHighestTensor_cartan _ _) (partitionHighestTensor_raising_zero _ _)
      (padSpectrum p k) =
    (rankSectorEmbedding mu hmu k).toContinuousLinearMap.comp
      ((sectorGibbsOperator (partitionHighestTensor mu hmu) mu
        (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p).comp
        (rankSectorEmbedding mu hmu k).toContinuousLinearMap.adjoint) := by
  apply ContinuousLinearMap.ext
  intro x
  apply (rankHighestIsometry mu hmu k).injective
  have he := highestCyclicIsometry_tensorOperator
    (partitionHighestTensor (padPartition mu k) (padPartition_antitone mu hmu k))
    (rankEmbeddedHighest mu hmu k) (fun a => (padPartition mu k a : ℂ))
    (partitionHighestTensor_cartan _ _) (rankEmbeddedHighest_weight mu hmu k)
    (partitionHighestTensor_raising_zero _ _) (rankEmbeddedHighest_raise mu hmu k)
    (partitionHighestTensor_norm _ _) (rankEmbeddedHighest_norm mu hmu k)
    (Matrix.diagonal (fun a => (padSpectrum p k a : ℂ))) x
  change rankHighestIsometry mu hmu k
      (sectorGibbsOperator _ _ _ _ (padSpectrum p k) x) = _ at he
  rw [he]
  change sectorGibbsOperator (coordinateTensorEmbedding _ r k (partitionHighestTensor mu hmu))
    (padPartition mu k)
    (coordinateTensorEmbedding_highest (partitionHighestTensor mu hmu) mu
      (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu)).1
    (coordinateTensorEmbedding_highest (partitionHighestTensor mu hmu) mu
      (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu)).2
    (padSpectrum p k) (rankHighestIsometry mu hmu k x) = _
  rw [coordinateSectorEmbedding_gibbs (partitionHighestTensor mu hmu) mu
    (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p]
  change coordinateSectorEmbedding (k := k) (partitionHighestTensor mu hmu)
    (sectorGibbsOperator (partitionHighestTensor mu hmu) mu
        (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p
      ((coordinateSectorEmbedding (k := k) (partitionHighestTensor mu hmu)).toContinuousLinearMap.adjoint
        (rankHighestIsometry mu hmu k x))) =
    rankHighestIsometry mu hmu k (rankSectorEmbedding mu hmu k
      (sectorGibbsOperator (partitionHighestTensor mu hmu) mu
        (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p ((rankSectorEmbedding mu hmu k).toContinuousLinearMap.adjoint x)))
  exact (congrArg (fun z : cyclicSector (partitionHighestTensor mu hmu) =>
    coordinateSectorEmbedding (k := k) (partitionHighestTensor mu hmu)
      (sectorGibbsOperator (partitionHighestTensor mu hmu) mu
        (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p z))
      (rankSectorEmbedding_adjoint_transport mu hmu k x)).symm.trans
        (rankHighestIsometry_embedding mu hmu k _).symm

/-- Trace-class form of exact Gibbs compression. -/
theorem sectorGibbsWeight_padSpectrum (mu : Fin r → ℕ) (hmu : Antitone mu)
    (k : ℕ) (p : Fin r → ℝ) :
    sectorGibbsWeight
      (partitionHighestTensor (padPartition mu k) (padPartition_antitone mu hmu k))
      (padPartition mu k) (partitionHighestTensor_cartan _ _) (partitionHighestTensor_raising_zero _ _)
      (padSpectrum p k) =
    conjugationLinearMap (rankSectorEmbedding mu hmu k).toContinuousLinearMap
      (sectorGibbsWeight (partitionHighestTensor mu hmu) mu
        (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p) := by
  apply Subtype.ext
  exact sectorGibbsOperator_padSpectrum mu hmu k p

/-- Rank compression preserves the normalization trace at every nonnegative
spectrum, including spectra with further zero entries. -/
theorem sectorPartitionFunction_padSpectrum (mu : Fin r → ℕ) (hmu : Antitone mu)
    (k : ℕ) (p : Fin r → ℝ) (hp : ∀a,0≤p a) :
    sectorPartitionFunction
      (partitionHighestTensor (padPartition mu k) (padPartition_antitone mu hmu k))
      (padPartition mu k) (partitionHighestTensor_cartan _ _) (partitionHighestTensor_raising_zero _ _)
      (padSpectrum p k) =
    sectorPartitionFunction (partitionHighestTensor mu hmu) mu
      (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p := by
  have ht := conjugationLinearMap_isometry_trace (rankSectorEmbedding mu hmu k)
    (sectorGibbsWeight (partitionHighestTensor mu hmu) mu
      (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p)
  rw [← sectorGibbsWeight_padSpectrum,trace_sectorGibbsWeight _ _ _ _ _ (padSpectrum_nonneg p hp k),
    trace_sectorGibbsWeight _ _ _ _ _ hp] at ht
  exact_mod_cast ht

/-- The conditional-support identity for supported nonnegative spectra. Both
sides use the actual physical Gibbs operators and are normalized when the
common partition function is positive (in particular, when every `p a>0`). -/
theorem sectorGibbsDensity_padSpectrum (mu : Fin r → ℕ) (hmu : Antitone mu)
    (k : ℕ) (p : Fin r → ℝ) (hp : ∀a,0≤p a) :
    sectorGibbsDensity
      (partitionHighestTensor (padPartition mu k) (padPartition_antitone mu hmu k))
      (padPartition mu k) (partitionHighestTensor_cartan _ _) (partitionHighestTensor_raising_zero _ _)
      (padSpectrum p k) =
    conjugationLinearMap (rankSectorEmbedding mu hmu k).toContinuousLinearMap
      (sectorGibbsDensity (partitionHighestTensor mu hmu) mu
        (partitionHighestTensor_cartan mu hmu) (partitionHighestTensor_raising_zero mu hmu) p) := by
  rw [sectorGibbsDensity,sectorPartitionFunction_padSpectrum mu hmu k p hp,
    sectorGibbsWeight_padSpectrum,sectorGibbsDensity,map_smul]

theorem physicalSectorCharacter_padSpectrum (mu : Fin r → ℕ) (hmu : Antitone mu)
    (k : ℕ) (p : Fin r → ℝ) (hp : ∀a,0≤p a) :
    physicalSectorCharacter (padPartition mu k) (padSpectrum p k)=physicalSectorCharacter mu p := by
  simp only [physicalSectorCharacter,dif_pos (padPartition_antitone mu hmu k),dif_pos hmu]
  exact sectorPartitionFunction_padSpectrum mu hmu k p hp

theorem physicalSectorCharacter_padSpectrum_pos (mu : Fin r → ℕ) (hmu : Antitone mu)
    (k : ℕ) (p : Fin r → ℝ) (hp : ∀a,0<p a) :
    0<physicalSectorCharacter (padPartition mu k) (padSpectrum p k) := by
  rw [physicalSectorCharacter_padSpectrum mu hmu k p (fun a => (hp a).le)]
  simp only [physicalSectorCharacter,dif_pos hmu]
  exact sectorPartitionFunction_pos _ _ _ _ (partitionHighestTensor_norm mu hmu) p hp

@[simp] theorem padSpectrum_sum (p : Fin r → ℝ) (k : ℕ) :
    ∑a,padSpectrum p k a=∑a,p a := by
  rw [Fin.sum_univ_add]
  simp only [padSpectrum_left,padSpectrum_right,Finset.sum_const_zero,add_zero]

end Cloning.TensorLie
