import Cloning.TensorFlatProjectorSectorSupport
import Cloning.TensorSchurDecompositionTrace

/-! The actual ambient cyclic copies generated by a smaller-rank physical decomposition. -/
noncomputable section
open scoped BigOperators Classical InnerProductSpace
namespace Cloning.TensorLie
open Cloning.PCT
set_option backward.isDefEq.respectTransparency false
set_option maxHeartbeats 1600000
set_option synthInstance.maxHeartbeats 200000
variable {n r d : ℕ}
local instance (n d : ℕ) : FiniteDimensional ℂ (TensorRegister n (Fin d)) :=
  (registerBasis (Fin n → Fin d)).toOrthonormalBasis.toBasis.finiteDimensional_of_finite

/-- Orthogonal normalized highest tensors generate orthogonal full cyclic copies. -/
theorem PhysicalHighestTensor.sector_orthogonal_of_inner_zero
    (H K : PhysicalHighestTensor n d) (hHK : ⟪H.vector,K.vector⟫_ℂ=0) : K.sector ≤ H.sectorᗮ := by
  apply cyclicSector_le_of_mem_of_invariant _
    (fun a b x hx => generatorInvariant_orthogonal H.sector
      (fun a b x hx => H.generator_invariant a b hx) a b hx)
  apply (H.sector.mem_orthogonal K.vector).mpr
  intro x hx
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨w,rfl⟩ := hx
    cases w with
    | nil => exact hHK
    | cons a w => exact inner_loweringWord_cons_eq_zero H.vector K.vector K.raising a w
  | zero => simp
  | add x y hx hy ihx ihy => simp only [inner_add_left,ihx,ihy,add_zero]
  | smul c x hx ih => simp only [inner_smul_left,ih,mul_zero]

def PhysicalHighestTensor.coordinateLift (H : PhysicalHighestTensor n r) (k : ℕ) :
    PhysicalHighestTensor n (r+k) where
  weight := padPartition H.weight k
  weight_antitone := padPartition_antitone H.weight H.weight_antitone k
  weight_sum := (sum_padPartition H.weight k).trans H.weight_sum
  vector := coordinateTensorEmbedding n r k H.vector
  norm_one := (coordinateTensorEmbedding n r k).norm_map H.vector |>.trans H.norm_one
  cartan := (coordinateTensorEmbedding_highest H.vector H.weight H.cartan H.raising).1
  raising := (coordinateTensorEmbedding_highest H.vector H.weight H.cartan H.raising).2

theorem coordinateLift_family_orthogonal {ι : Type*} (H : ι → PhysicalHighestTensor n r)
    (hH : OrthogonalFamily ℂ (fun i => (H i).sector) (fun i => (H i).sector.subtypeₗᵢ))
    (k : ℕ) :
    OrthogonalFamily ℂ (fun i => ((H i).coordinateLift k).sector)
      (fun i => ((H i).coordinateLift k).sector.subtypeₗᵢ) := by
  intro i j hij x y
  apply (((H i).coordinateLift k).sector.mem_orthogonal _).mp
    (PhysicalHighestTensor.sector_orthogonal_of_inner_zero _ _ ?_ y.property) x x.property
  change ⟪coordinateTensorEmbedding n r k (H i).vector,
    coordinateTensorEmbedding n r k (H j).vector⟫_ℂ=0
  rw [LinearIsometry.inner_map_map]
  exact hH hij ⟨_,(H i).vector_mem⟩ ⟨_,(H j).vector_mem⟩

theorem PhysicalHighestTensor.canonicalEmbedding_loweringWord (H : PhysicalHighestTensor n d)
    (w : List (PositiveRoot d)) :
    H.canonicalEmbedding ⟨loweringWord (partitionHighestTensor H.weight H.weight_antitone) w,
      loweringWord_mem_cyclicSector _ w⟩ = loweringWord H.vector w := by
  exact highestCyclicIsometry_loweringWord (partitionHighestTensor H.weight H.weight_antitone) H.vector
    (fun a => (H.weight a : ℂ)) (partitionHighestTensor_cartan _ _) H.cartan
    (partitionHighestTensor_raising_zero _ _) H.raising (partitionHighestTensor_norm _ _) H.norm_one w

/-- The canonical phase choices agree exactly with coordinate tensor inclusion. -/
theorem PhysicalHighestTensor.coordinateLift_canonicalEmbedding
    (H : PhysicalHighestTensor n r) (k : ℕ) (x : H.CanonicalSector) :
    (H.coordinateLift k).canonicalEmbedding (rankSectorEmbedding H.weight H.weight_antitone k x) =
      coordinateTensorEmbedding n r k (H.canonicalEmbedding x) := by
  let f := (H.coordinateLift k).canonicalEmbedding.toLinearMap.comp
    (rankSectorEmbedding H.weight H.weight_antitone k).toLinearMap
  let g := (coordinateTensorEmbedding n r k).toLinearMap.comp H.canonicalEmbedding.toLinearMap
  change f x=g x
  obtain ⟨x,hx⟩ := x
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨w,rfl⟩ := hx
    have he := rankSectorEmbedding_loweringWord H.weight H.weight_antitone k w
    have he' : rankSectorEmbedding H.weight H.weight_antitone k
        ⟨loweringWord (partitionHighestTensor H.weight H.weight_antitone) w,loweringWord_mem_cyclicSector _ w⟩ =
        ⟨loweringWord (partitionHighestTensor (padPartition H.weight k) (padPartition_antitone _ H.weight_antitone k))
          (w.map coordinateRoot),loweringWord_mem_cyclicSector _ _⟩ := Subtype.ext he
    change (H.coordinateLift k).canonicalEmbedding (rankSectorEmbedding _ _ _ _) =
      coordinateTensorEmbedding n r k (H.canonicalEmbedding _)
    rw [he',H.canonicalEmbedding_loweringWord]
    exact ((H.coordinateLift k).canonicalEmbedding_loweringWord (w.map coordinateRoot)).trans
      (coordinateTensorEmbedding_loweringWord H.vector w).symm
  | zero => change f 0=g 0; simp
  | add x y hx hy ihx ihy =>
    change f (⟨x,hx⟩+⟨y,hy⟩)=g (⟨x,hx⟩+⟨y,hy⟩)
    rw [map_add,map_add,ihx,ihy]
  | smul c x hx ih =>
    change f (c • ⟨x,hx⟩)=g (c • ⟨x,hx⟩)
    rw [map_smul,map_smul,ih]

end Cloning.TensorLie
