import Cloning.TensorCyclicFiltration
import Cloning.TensorPartitionHighest
import Mathlib.Analysis.InnerProductSpace.Projection.FiniteDimensional

/-! Full physical cyclic sectors and uniqueness of their highest line. -/
noncomputable section
open scoped BigOperators InnerProductSpace
namespace Cloning.TensorLie
set_option maxHeartbeats 1000000
set_option backward.isDefEq.respectTransparency false
variable {n d : ℕ}

/-- The full cyclic sector generated by actual lowering operators. -/
def cyclicSector (Ω : TensorRegister n (Fin d)) : Submodule ℂ (TensorRegister n (Fin d)) :=
  Submodule.span ℂ (Set.range (loweringWord Ω))

theorem loweringWord_mem_cyclicSector (Ω : TensorRegister n (Fin d))
    (w : List (PositiveRoot d)) : loweringWord Ω w ∈ cyclicSector Ω :=
  Submodule.subset_span (Set.mem_range_self w)

theorem highest_mem_cyclicSector (Ω : TensorRegister n (Fin d)) : Ω ∈ cyclicSector Ω :=
  loweringWord_mem_cyclicSector Ω []

theorem cyclicCutoff_le_cyclicSector (Ω : TensorRegister n (Fin d)) (r : ℤ) :
    cyclicCutoff Ω r ≤ cyclicSector Ω := by
  apply Submodule.span_le.mpr
  rintro x ⟨w, _, rfl⟩
  exact loweringWord_mem_cyclicSector Ω w

/-- The full cyclic space is invariant under every literal matrix-unit generator. -/
theorem cyclicSector_generator_invariant
    (Ω : TensorRegister n (Fin d)) (mu : Fin d → ℂ)
    (hweight : ∀ a, collectiveGenerator n a a Ω = mu a • Ω)
    (hraise : ∀ a b, a < b → collectiveGenerator n a b Ω = 0)
    (a b : Fin d) {x : TensorRegister n (Fin d)} (hx : x ∈ cyclicSector Ω) :
    collectiveGenerator n a b x ∈ cyclicSector Ω := by
  have h : cyclicSector Ω ≤ (cyclicSector Ω).comap (collectiveGenerator n a b).toLinearMap := by
    apply Submodule.span_le.mpr
    rintro x ⟨w, rfl⟩
    exact cyclicCutoff_le_cyclicSector Ω _
      (generator_loweringWord_mem Ω mu hweight hraise w a b)
  exact h hx

/-- A vector killed by every raising operator is orthogonal to every nonempty
lowering word. This uses the actual adjoint relation, not irreducibility. -/
theorem inner_loweringWord_cons_eq_zero
    (Ω x : TensorRegister n (Fin d))
    (hx : ∀ a b, a < b → collectiveGenerator n a b x = 0)
    (a : PositiveRoot d) (w : List (PositiveRoot d)) :
    ⟪loweringWord Ω (a :: w), x⟫_ℂ = 0 := by
  rw [loweringWord, ← ContinuousLinearMap.adjoint_inner_right,
    collectiveGenerator_adjoint, hx a.val.1 a.val.2 a.property, inner_zero_right]

/-- The joint raising kernel within a cyclic highest sector is precisely its
highest line. No representation classification or independence premise occurs. -/
theorem cyclicSector_raising_kernel
    (Ω : TensorRegister n (Fin d)) (hΩ : ‖Ω‖ = 1)
    (hraise : ∀ a b, a < b → collectiveGenerator n a b Ω = 0)
    {x : TensorRegister n (Fin d)} (hx : x ∈ cyclicSector Ω)
    (hxraise : ∀ a b, a < b → collectiveGenerator n a b x = 0) :
    x = ⟪Ω, x⟫_ℂ • Ω := by
  let y := x - ⟪Ω, x⟫_ℂ • Ω
  have hy : y ∈ cyclicSector Ω := (cyclicSector Ω).sub_mem hx
    ((cyclicSector Ω).smul_mem _ (highest_mem_cyclicSector Ω))
  have hyraise : ∀ a b, a < b → collectiveGenerator n a b y = 0 := by
    intro a b hab
    simp only [y, map_sub, map_smul, hxraise a b hab, hraise a b hab, smul_zero, sub_zero]
  have hΩinner : ⟪Ω, Ω⟫_ℂ = 1 := by
    rw [inner_self_eq_norm_sq_to_K, hΩ]
    norm_num
  have hΩy : ⟪Ω, y⟫_ℂ = 0 := by
    simp only [y, inner_sub_right, inner_smul_right, hΩinner, mul_one, sub_self]
  have horth : ∀ z ∈ cyclicSector Ω, ⟪z, y⟫_ℂ = 0 := by
    intro z hz
    induction hz using Submodule.span_induction with
    | mem z hz =>
      obtain ⟨w, rfl⟩ := hz
      cases w with
      | nil => exact hΩy
      | cons a w => exact inner_loweringWord_cons_eq_zero Ω y hyraise a w
    | zero => simp
    | add u v hu hv ihu ihv => simp [inner_add_left, ihu, ihv]
    | smul c z hz ih => simp [inner_smul_left, ih]
  have hyzero : y = 0 := (inner_self_eq_zero).mp (horth y hy)
  exact sub_eq_zero.mp hyzero

theorem cyclicSector_raising_iff
    (Ω : TensorRegister n (Fin d)) (hΩ : ‖Ω‖ = 1)
    (hraise : ∀ a b, a < b → collectiveGenerator n a b Ω = 0)
    {x : TensorRegister n (Fin d)} (hx : x ∈ cyclicSector Ω) :
    (∀ a b, a < b → collectiveGenerator n a b x = 0) ↔
      x ∈ Submodule.span ℂ {Ω} := by
  constructor
  · intro h
    rw [cyclicSector_raising_kernel Ω hΩ hraise hx h]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton Ω))
  · intro h a b hab
    obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp h
    simp only [map_smul, hraise a b hab, smul_zero]

/-- Every endomorphism of the physical cyclic sector commuting with all actual
matrix units is scalar on that sector. -/
theorem cyclicSector_commutant_scalar
    (Ω : TensorRegister n (Fin d)) (hΩ : ‖Ω‖ = 1)
    (hraise : ∀ a b, a < b → collectiveGenerator n a b Ω = 0)
    (T : TensorRegister n (Fin d) →ₗ[ℂ] TensorRegister n (Fin d))
    (hT : ∀ x ∈ cyclicSector Ω, T x ∈ cyclicSector Ω)
    (hcomm : ∀ a b x, x ∈ cyclicSector Ω →
      T (collectiveGenerator n a b x) = collectiveGenerator n a b (T x)) :
    ∃ c : ℂ, ∀ x ∈ cyclicSector Ω, T x = c • x := by
  let c := ⟪Ω, T Ω⟫_ℂ
  have hTΩ : T Ω = c • Ω := by
    apply cyclicSector_raising_kernel Ω hΩ hraise (hT Ω (highest_mem_cyclicSector Ω))
    intro a b hab
    rw [← hcomm a b Ω (highest_mem_cyclicSector Ω), hraise a b hab, map_zero]
  have hword : ∀ w, T (loweringWord Ω w) = c • loweringWord Ω w := by
    intro w
    induction w with
    | nil => exact hTΩ
    | cons a w ih =>
      rw [loweringWord, hcomm a.val.2 a.val.1 _ (loweringWord_mem_cyclicSector Ω w), ih,
        map_smul]
  refine ⟨c, ?_⟩
  intro x hx
  induction hx using Submodule.span_induction with
  | mem x hx => obtain ⟨w, rfl⟩ := hx; exact hword w
  | zero => simp
  | add x y hx hy ihx ihy => simp [map_add, ihx, ihy, smul_add]
  | smul a x hx ih => simp [map_smul, ih, smul_smul, mul_comm]

end Cloning.TensorLie
